@extends('layouts.app')

@section('title', 'Payroll')

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="h4 mb-0">Payroll Runs</h1>
        @can('payroll.generate')
            <a href="{{ route('payroll.create') }}" class="btn btn-primary btn-sm">
                <i class="bi bi-plus-lg"></i> Generate Payroll Run
            </a>
        @endcan
    </div>

    <div class="card shadow-sm">
        <div class="table-responsive">
            <table class="table table-hover mb-0 align-middle">
                <thead>
                    <tr>
                        <th>Period</th>
                        <th class="text-end">Employees</th>
                        <th>Status</th>
                        <th>Generated By</th>
                        <th>Approved By</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($runs as $run)
                        <tr>
                            <td>{{ $run->period_start->format('Y-m-d') }} to {{ $run->period_end->format('Y-m-d') }}</td>
                            <td class="text-end">{{ $run->items_count }}</td>
                            <td>
                                <span class="badge {{ match ($run->status) {
                                    'draft' => 'bg-secondary',
                                    'approved' => 'bg-warning text-dark',
                                    'paid' => 'bg-success',
                                    default => 'bg-danger',
                                } }}">
                                    {{ str($run->status)->headline() }}
                                </span>
                            </td>
                            <td>{{ $run->generatedBy?->name ?? '—' }}</td>
                            <td>{{ $run->approvedBy?->name ?? '—' }}</td>
                            <td class="text-end">
                                <a href="{{ route('payroll.show', $run) }}" class="btn btn-sm btn-outline-secondary">
                                    <i class="bi bi-eye"></i> View
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-center text-muted py-4">No payroll runs yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-3">
        {{ $runs->links() }}
    </div>
@endsection
