@extends('layouts.app')

@section('title', 'Payroll Run')

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
            <h1 class="h4 mb-0">Payroll Run — {{ $payrollRun->period_start->format('Y-m-d') }} to {{ $payrollRun->period_end->format('Y-m-d') }}</h1>
            <div class="text-muted small">
                Generated by {{ $payrollRun->generatedBy?->name ?? '—' }}
                @if ($payrollRun->approvedBy)
                    &middot; Approved by {{ $payrollRun->approvedBy->name }} on {{ $payrollRun->approved_at->format('Y-m-d H:i') }}
                @endif
                @if ($payrollRun->paid_at)
                    &middot; Paid on {{ $payrollRun->paid_at->format('Y-m-d H:i') }}
                @endif
            </div>
        </div>
        <div class="d-flex align-items-center gap-2">
            <span class="badge fs-6 {{ match ($payrollRun->status) {
                'draft' => 'bg-secondary',
                'approved' => 'bg-warning text-dark',
                'paid' => 'bg-success',
                default => 'bg-danger',
            } }}">
                {{ str($payrollRun->status)->headline() }}
            </span>
            @can('payroll.approve')
                @if ($payrollRun->canBeApproved())
                    <form method="POST" action="{{ route('payroll.approve', $payrollRun) }}" onsubmit="return confirm('Approve this payroll run? Payslips will be locked from further adjustments.');">
                        @csrf
                        <button type="submit" class="btn btn-sm btn-warning">Approve</button>
                    </form>
                @endif
            @endcan
            @can('payroll.pay')
                @if ($payrollRun->canBeMarkedPaid())
                    <form method="POST" action="{{ route('payroll.pay', $payrollRun) }}" onsubmit="return confirm('Mark this payroll run as paid? This will post delivery earnings payouts to each rider\'s wallet.');">
                        @csrf
                        <button type="submit" class="btn btn-sm btn-success">Mark Paid</button>
                    </form>
                @endif
            @endcan
        </div>
    </div>

    @if ($payrollRun->notes)
        <div class="alert alert-light border small">{{ $payrollRun->notes }}</div>
    @endif

    <div class="card shadow-sm">
        <div class="table-responsive">
            <table class="table table-hover mb-0 align-middle">
                <thead>
                    <tr>
                        <th>Employee</th>
                        <th class="text-end">Basic Salary</th>
                        <th class="text-end">Delivery Earnings</th>
                        <th class="text-end">Gross Pay</th>
                        <th class="text-end">Deductions</th>
                        <th class="text-end">Net Pay</th>
                        <th class="text-end">Adjustments</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($payrollRun->items as $item)
                        <tr>
                            <td>{{ $item->employee->user->name }}</td>
                            <td class="text-end">{{ number_format($item->basic_salary, 2) }}</td>
                            <td class="text-end">{{ number_format($item->delivery_earnings, 2) }}</td>
                            <td class="text-end">{{ number_format($item->gross_pay, 2) }}</td>
                            <td class="text-end">{{ number_format($item->total_deductions, 2) }}</td>
                            <td class="text-end fw-semibold">{{ number_format($item->net_pay, 2) }}</td>
                            <td class="text-end">
                                <button class="btn btn-sm btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#adj-{{ $item->id }}">
                                    {{ $item->adjustments->count() }} <i class="bi bi-chevron-down"></i>
                                </button>
                            </td>
                        </tr>
                        <tr class="collapse" id="adj-{{ $item->id }}">
                            <td colspan="7" class="bg-light">
                                @if ($item->adjustments->isEmpty())
                                    <div class="text-muted small py-2">No adjustments.</div>
                                @else
                                    <table class="table table-sm mb-2">
                                        <thead>
                                            <tr>
                                                <th>Type</th>
                                                <th>Label</th>
                                                <th class="text-end">Amount</th>
                                                <th>Linked Advance</th>
                                                @if ($payrollRun->isEditable())
                                                    <th></th>
                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($item->adjustments as $adjustment)
                                                <tr>
                                                    <td>
                                                        <span class="badge {{ $adjustment->type === 'addition' ? 'bg-success' : 'bg-danger' }}">
                                                            {{ str($adjustment->type)->headline() }}
                                                        </span>
                                                    </td>
                                                    <td>{{ $adjustment->label }}</td>
                                                    <td class="text-end">{{ number_format($adjustment->amount, 2) }}</td>
                                                    <td>{{ $adjustment->employeeAdvance ? 'Advance ('.number_format($adjustment->employeeAdvance->remaining_balance, 2).' left)' : '—' }}</td>
                                                    @if ($payrollRun->isEditable())
                                                        <td>
                                                            @can('payroll.generate')
                                                                <form method="POST" action="{{ route('payroll.adjustments.destroy', $adjustment) }}" onsubmit="return confirm('Remove this adjustment?');">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit" class="btn btn-sm btn-link text-danger p-0">Remove</button>
                                                                </form>
                                                            @endcan
                                                        </td>
                                                    @endif
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                @endif

                                @can('payroll.generate')
                                    @if ($payrollRun->isEditable())
                                        <form method="POST" action="{{ route('payroll.adjustments.store', $item) }}" class="row g-2 align-items-end py-2">
                                            @csrf
                                            <div class="col-md-2">
                                                <select name="type" class="form-select form-select-sm">
                                                    <option value="deduction">Deduction</option>
                                                    <option value="addition">Addition</option>
                                                </select>
                                            </div>
                                            <div class="col-md-3">
                                                <input type="text" name="label" class="form-control form-control-sm" placeholder="Label" required>
                                            </div>
                                            <div class="col-md-2">
                                                <input type="number" step="0.01" min="0.01" name="amount" class="form-control form-control-sm" placeholder="Amount" required>
                                            </div>
                                            @if (($advancesByEmployee[$item->employee_id] ?? collect())->isNotEmpty())
                                                <div class="col-md-3">
                                                    <select name="employee_advance_id" class="form-select form-select-sm">
                                                        <option value="">No linked advance</option>
                                                        @foreach ($advancesByEmployee[$item->employee_id] as $advance)
                                                            <option value="{{ $advance->id }}">
                                                                {{ $advance->date_given->format('Y-m-d') }} — {{ number_format($advance->remaining_balance, 2) }} left
                                                            </option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            @endif
                                            <div class="col-md-2">
                                                <button type="submit" class="btn btn-sm btn-primary w-100">Add</button>
                                            </div>
                                        </form>
                                    @endif
                                @endcan
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="text-center text-muted py-4">No employees included in this run.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-3">
        <a href="{{ route('payroll.index') }}" class="btn btn-link">Back to Payroll Runs</a>
    </div>
@endsection
